version: "3.9"

services:
  mf_dbz:
    build: 
      context: mf_dbz
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - mf_navbar
      - mf_vue_cards
  mf_vue_cards:
    build: 
      context: mf_vue_cards
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
  mf_navbar:
    build: 
      context: mf_navbar
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
  mf_card_detail:
    build: 
      context: mf_card_detail
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    
  